### ISSUE TITLE
'ignore' library enforcing default settings, and it's undisableable

### ISSUE THREAD

**Issue by L1lith** [standard/deglob#17]
**What version of this package are you using?**
4.0.1
**What problem do you want to solve?**
The default ignore settings imported by the 'ignore' package cannot be disabled. I am currently working on a project, and I've hit a giant wall as I'm not able to copy my .gitignore and other different kinds of automatically ignored files. This is necessary as I'm working on [my template generation library](https://github.com/l1lith/emerald-templates), and I'm not able to copy the files properly from the template folders.
**What do you think is the correct solution to this problem?**
Add a flag to enable or disable the default settings imparted by the 'ignore' package.
**Are you willing to submit a pull request to implement this change?**
Possibly, unsure.

**Comment by feross** [comment]
There's an option for this. Set `noDefaultIgnore` to `true`.
