### ISSUE TITLE
Why is there a path dependency?

### ISSUE THREAD

**Issue by novemberborn** [standard/deglob#2]
Why is there a dependency on the https://www.npmjs.com/package/path package? Normal `require('path')` will provide the internal module AFAICT, which means the package is installed but never used. It didn't seem to be a dependency in standard (given https://github.com/feross/standard/pull/187 where it switched to deglob) so perhaps this was by accident?

With npm@3  it's being installed as a top-level dependency, and another package which uses Node's private module loading methods ends up loading the fake `path`. The version requested doesn't work correctly under Node 5 (but it'd always be out of date anyway).

**Comment by Flet** [comment]
Good catch! This should be removed!

**Comment by feross** [comment]
Fixed and released as 1.0.2.
